# Generated by Django 4.2.3 on 2023-07-18 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0002_product'),
        ('app_buyer', '0007_alter_user_propic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_buyer.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_app.product')),
            ],
        ),
    ]
